### ISSUE TITLE
Cannot find the full Samsung S10 dataset

### ISSUE THREAD

**Issue by lekhang4497** [anon-submission2020/Anonymous-Submission-EMNLP2021#2]
Dear author,
In experiments in the paper are conducted on the Samsung S10 dataset. However, I cannot find the Samsung S10 full dataset in the `data` folder (I can only find 50 QA pair examples). Will the full dataset be published?

Thank you very much.

**Comment by abhi1nandy2** [comment]
Please check https://github.com/abhi1nandy2/EMNLP-2021-Findings/issues/1
