### ISSUE TITLE
License for the released Smart TV/remote QA data

### ISSUE THREAD

**Issue by h366lj3** [anon-submission2020/Anonymous-Submission-EMNLP2021#6]
Hi, 
For the released 684 samples for Smart TV/remote QA, I could not locate a clear indication of any sort of license terms. The only relevant info I could find is this closed issue (https://github.com/abhi1nandy2/EMNLP-2021-Findings/issues/1#issuecomment-1080094627), where you mentioned "Also, since this project was in collaboration with Samsung, we are unable to provide with the full S10 QA Dataset at this time. However, the questions follow the format of data/smart_remote_QA.zip, and I would request you to use that for the time being. Also, if you would like to use our code/data, we request you to cite our paper."

Can you please put a license for the released Smart TV/remote QA data? 

Thanks!

**Comment by abhi1nandy2** [comment]
We have put a license on the repo.
